EJERCICIOS DE CREACIÓN DE ARRAYS

In [1]:
# Importamos la librería numpy
 
import numpy as np

# Ejercicios

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 



In [2]:
size = (4, 3)

low = 34

high = 99

mi_array = np.random.randint(low, high, size)

print(mi_array)

[[34 44 85]
 [42 44 74]
 [45 61 47]
 [68 51 83]]


2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.

In [3]:
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

a_unidim = np.array(lista1)
a_bidim = np.array(lista2)

print(a_unidim)
print(f"\nLas dimensiones del array son {a_unidim.shape}. El nº de dimensiones es: {a_unidim.ndim}. El nº total de elementos es {a_unidim.size}. Y el tipo de datos es {a_unidim.dtype}")
print("\n********************\n")
print(a_bidim)
print(f"\nLas dimensiones del array son {a_bidim.shape}. El nº de dimensiones es: {a_bidim.ndim}. El nº total de elementos es {a_bidim.size}. Y el tipo de datos es {a_bidim.dtype}")
print("\n********************\n")




[34 56 71 98 10]

Las dimensiones del array son (5,). El nº de dimensiones es: 1. El nº total de elementos es 5. Y el tipo de datos es int64

********************

[[23 45 89 56]
 [12 43 82 44]]

Las dimensiones del array son (2, 4). El nº de dimensiones es: 2. El nº total de elementos es 8. Y el tipo de datos es int64

********************



EJERCICIOS DE INDEXACIÓN 

1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

In [4]:
mi_array = np.random.randint(1, 20, 50)
print(mi_array)
print(f"El primer elemento es: {mi_array[0]}")
print(f"Los elementos en posiciones impares son: {mi_array[1::2]}")
print(f"Los primeros cuatro elementos son: {mi_array[0:4]}")
print(f"Los últimos tres elementos son: {mi_array[47:50]}")
print(f"Los elementos entre el 4 y el 8 (incluido): {mi_array[4:9]}")


[16  9  3  7  1  1 13  4 19 11 13  2 19 18 11 18 11 10 17  4 16  8 14  8
 13 14  2 11  6 11  9  9  4  9  9  2 11  4 13 10 12  6 19  4 15 17  7  7
  8  1]
El primer elemento es: 16
Los elementos en posiciones impares son: [ 9  7  1  4 11  2 18 18 10  4  8  8 14 11 11  9  9  2  4 10  6  4 17  7
  1]
Los primeros cuatro elementos son: [16  9  3  7]
Los últimos tres elementos son: [7 8 1]
Los elementos entre el 4 y el 8 (incluido): [ 1  1 13  4 19]


2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.


In [5]:
bidimensional = np.random.rand(4, 5)
print(bidimensional)

print(f"La primera fila y todas las columnas {bidimensional[0, : ]}")
print(f"Todas las filas pares {bidimensional[1::2, :]}")
print(f"La primera columna y todas las filas: {bidimensional[:,0]}")

[[0.43526575 0.46993312 0.37753844 0.2075257  0.97270582]
 [0.65426473 0.55575911 0.34965555 0.0573457  0.97112023]
 [0.96537666 0.03350153 0.28947496 0.61406477 0.02929238]
 [0.8189965  0.9931804  0.03301425 0.97520014 0.9065869 ]]
La primera fila y todas las columnas [0.43526575 0.46993312 0.37753844 0.2075257  0.97270582]
Todas las filas pares [[0.65426473 0.55575911 0.34965555 0.0573457  0.97112023]
 [0.8189965  0.9931804  0.03301425 0.97520014 0.9065869 ]]
La primera columna y todas las filas: [0.43526575 0.65426473 0.96537666 0.8189965 ]


FILTRADO Y OPERACIONES ARITMÉTICAS

# Ejercicios


1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [6]:
mi_array = np.random.randint(0, 51, (4,5))
print(mi_array)
resultados_filtrados = np.where((mi_array > 30) | (mi_array < 10), "objetivo", "no es mi objetivo")
print(resultados_filtrados)

[[37 26 20 18  7]
 [ 1 35  3 23 18]
 [ 6 20 44  8  2]
 [34 41  1 12 19]]
[['objetivo' 'no es mi objetivo' 'no es mi objetivo' 'no es mi objetivo'
  'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'no es mi objetivo'
  'no es mi objetivo']
 ['objetivo' 'no es mi objetivo' 'objetivo' 'objetivo' 'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'no es mi objetivo'
  'no es mi objetivo']]


In [7]:
print(mi_array)
resultado = 10*mi_array
print(f"El resultado de multiplicar el array por el escalar 10 es:\n{resultado}")

[[37 26 20 18  7]
 [ 1 35  3 23 18]
 [ 6 20 44  8  2]
 [34 41  1 12 19]]
El resultado de multiplicar el array por el escalar 10 es:
[[370 260 200 180  70]
 [ 10 350  30 230 180]
 [ 60 200 440  80  20]
 [340 410  10 120 190]]


In [11]:
mi_array = np.random.randint(0, 51, (4,5))
print(mi_array)
resultados_filtrados = np.where((mi_array > 30) | (mi_array < 10))
print(resultados_filtrados)

[[49 47  4 17 13]
 [23 13 28  5 46]
 [10 21 48 16 14]
 [27  0  1  7 34]]
(array([0, 0, 0, 1, 1, 2, 3, 3, 3, 3]), array([0, 1, 2, 3, 4, 2, 1, 2, 3, 4]))



2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiz lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.


In [8]:
mi_array = np.random.randint(0, 51, (4,5))
print("mi_array\n", mi_array)

array2 = np.random.randint(0, 51, (4, 5))
print("array2\n", array2)

suma = np.add(mi_array, array2)
print("suma\n", suma)

resta = np.subtract(mi_array, array2)
print("resta\n", resta)

multiplicacion = np.multiply(mi_array, array2)
print("multiplicacion\n", multiplicacion)

division = np.divide(mi_array, array2)
print("division\n", division)

potencia = np.power(mi_array, array2)
print("potencia\n", potencia)

print(f"El primer array elevado al segundo es\n{potencia}")


mi_array
 [[ 5 26 45 49 19]
 [35  7 23  3 17]
 [46 45 32 23  6]
 [ 9 21 33  4 35]]
array2
 [[16 16  0 26 37]
 [23 39 45 12 36]
 [40 36 49  2 11]
 [ 7 21 43 18 36]]
suma
 [[21 42 45 75 56]
 [58 46 68 15 53]
 [86 81 81 25 17]
 [16 42 76 22 71]]
resta
 [[-11  10  45  23 -18]
 [ 12 -32 -22  -9 -19]
 [  6   9 -17  21  -5]
 [  2   0 -10 -14  -1]]
multiplicacion
 [[  80  416    0 1274  703]
 [ 805  273 1035   36  612]
 [1840 1620 1568   46   66]
 [  63  441 1419   72 1260]]
division
 [[ 0.3125      1.625              inf  1.88461538  0.51351351]
 [ 1.52173913  0.17948718  0.51111111  0.25        0.47222222]
 [ 1.15        1.25        0.65306122 11.5         0.54545455]
 [ 1.28571429  1.          0.76744186  0.22222222  0.97222222]]
potencia
 [[-2030932031   608239616           1  1798631905 -1570507325]
 [-1049539541   593264119  2112869559      531441 -2116437951]
 [          0   124749457           0         529   362797056]
 [    4782969   878082373    88645985           0   169252945]]
El

C:\Users\anabo\AppData\Local\Temp\ipykernel_33932\821949242.py:16: RuntimeWarning: divide by zero encountered in divide
  division = np.divide(mi_array, array2)


FUNCIONES


1. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

    📝 **NOTA** En este ejercicio os hemos pedido algunos de los métodos, pero sentiros libres de practicar otros para ir asentando los conocimientos. 

In [9]:
array = np.random.randint(5,101, (3,2))
print(array)

[[87 67]
 [65 30]
 [11 92]]


In [10]:
media = np.mean(array)
print(f"La media de los elementos es {media}")

media_c = np.mean(array, axis = 0)
print(f"La media de las columnas es {media_c}")

redondeado = np.round(media_c, 2)
print(f"La media redondeada de las columnas es {redondeado}")

print(f"El valor máximo de cada fila es {np.max(array, axis = 1)}")

print(f"El valor minimo de cada fila es {np.min(array, axis = 1)}")

mayor_de_90 = np.where(array > 90)

print(f"Los elementos mayores de 90 están en {mayor_de_90}")

array_mayor_a_menor = -(np.sort(-array))

print(f"El array ordenado de mayor a menor es\n{array_mayor_a_menor}")
      





La media de los elementos es 58.666666666666664
La media de las columnas es [54.33333333 63.        ]
La media redondeada de las columnas es [54.33 63.  ]
El valor máximo de cada fila es [87 65 92]
El valor minimo de cada fila es [67 30 11]
Los elementos mayores de 90 están en (array([2]), array([1]))
El array ordenado de mayor a menor es
[[87 67]
 [65 30]
 [92 11]]
