# Creación e Indexación:


1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np

In [2]:
array1 = np.random.randint(10, 100, size = 50)
print(array1)

[26 86 84 68 21 87 18 11 48 92 15 18 52 65 98 54 90 55 20 61 54 45 73 21
 20 13 26 23 91 18 56 46 85 32 74 32 63 26 96 97 17 34 23 58 98 41 55 66
 75 52]


In [7]:
multiplos5 = array1[5::5]
multiplos5

array([87, 15, 54, 54, 13, 56, 32, 17, 41])

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
array2 = np.random.randint(1, 21, size = 30)
array2

array([10, 16,  1,  8,  1, 16, 19, 12, 15,  1,  4, 19, 13,  5, 20, 13, 16,
       15,  2,  4,  3,  9,  9, 13, 17,  3,  8,  3, 12, 16])

In [6]:
array2[1::2]

array([16,  8, 16, 12,  1, 19,  5, 13, 15,  4,  9, 13,  3,  3, 16])

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [12]:
array_sum1 =np.random.randint(0, 20, (4,6)) 
array_sum1

array([[ 9,  2, 10,  6,  3,  8],
       [ 6,  1,  1, 11,  4,  4],
       [11, 13,  2, 10, 19,  5],
       [13,  8, 11, 12,  3, 13]])

In [13]:
array_sum2 =np.random.rand(4,6)
array_sum2

array([[0.83758817, 0.94029314, 0.59321607, 0.38850578, 0.13352762,
        0.71327395],
       [0.29928992, 0.1129729 , 0.94497174, 0.22964028, 0.92762593,
        0.32605628],
       [0.55074358, 0.92118251, 0.04222957, 0.59967428, 0.59053983,
        0.9203555 ],
       [0.95454345, 0.53291975, 0.0912401 , 0.71541106, 0.92607097,
        0.38763743]])

In [14]:
# Sumamos los dos array

suma_array = np.add(array_sum1, array_sum2)
suma_array

array([[ 9.83758817,  2.94029314, 10.59321607,  6.38850578,  3.13352762,
         8.71327395],
       [ 6.29928992,  1.1129729 ,  1.94497174, 11.22964028,  4.92762593,
         4.32605628],
       [11.55074358, 13.92118251,  2.04222957, 10.59967428, 19.59053983,
         5.9203555 ],
       [13.95454345,  8.53291975, 11.0912401 , 12.71541106,  3.92607097,
        13.38763743]])

In [15]:
# Redondeamos a 2 decimales

redondeo = np.round(suma_array, 2)
redondeo

array([[ 9.84,  2.94, 10.59,  6.39,  3.13,  8.71],
       [ 6.3 ,  1.11,  1.94, 11.23,  4.93,  4.33],
       [11.55, 13.92,  2.04, 10.6 , 19.59,  5.92],
       [13.95,  8.53, 11.09, 12.72,  3.93, 13.39]])

In [16]:
# Accedo a la última fila de la matriz

ultima_fila = redondeo[-1]
ultima_fila

array([13.95,  8.53, 11.09, 12.72,  3.93, 13.39])

4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

# Reshape y Transpose:


## Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [17]:
array_3d = np.random.randint(1, 101, (2,3,4)) 
array_3d

array([[[28, 43, 93,  9],
        [63, 60, 35, 82],
        [59, 82, 23,  7]],

       [[63, 10, 44, 18],
        [34, 30, 82, 54],
        [28, 29, 78, 35]]])

In [18]:
array_reshape = np.reshape(array_3d,(12,2))
array_reshape

array([[28, 43],
       [93,  9],
       [63, 60],
       [35, 82],
       [59, 82],
       [23,  7],
       [63, 10],
       [44, 18],
       [34, 30],
       [82, 54],
       [28, 29],
       [78, 35]])

In [19]:
# Order (C y F)

array_reshape = np.reshape(array_3d,(12,2), 'C')
array_reshape


array([[28, 43],
       [93,  9],
       [63, 60],
       [35, 82],
       [59, 82],
       [23,  7],
       [63, 10],
       [44, 18],
       [34, 30],
       [82, 54],
       [28, 29],
       [78, 35]])

In [20]:

array_reshape = np.reshape(array_3d,(12,2), 'F')
array_reshape

array([[28, 93],
       [63, 44],
       [63, 35],
       [34, 82],
       [59, 23],
       [28, 78],
       [43,  9],
       [10, 18],
       [60, 82],
       [30, 54],
       [82,  7],
       [29, 35]])

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [21]:
array_3d2 = np.random.randint(1, 61, (3,4,5)) 
array_3d2

array([[[11, 11, 42,  6, 17],
        [60, 36, 10, 52, 13],
        [56, 11, 19, 24, 35],
        [44, 31, 53, 14, 45]],

       [[31, 59, 12,  5, 26],
        [31, 38, 33, 29, 48],
        [35,  2, 10, 50, 51],
        [10, 34, 58,  4, 18]],

       [[46, 19, 29, 30, 55],
        [12,  2, 49,  1, 27],
        [ 3, 56, 18, 42,  3],
        [45, 30, 17, 52, 11]]])

In [22]:
array_reshape2 = np.reshape(array_3d2,(2,30))
array_reshape2

array([[11, 11, 42,  6, 17, 60, 36, 10, 52, 13, 56, 11, 19, 24, 35, 44,
        31, 53, 14, 45, 31, 59, 12,  5, 26, 31, 38, 33, 29, 48],
       [35,  2, 10, 50, 51, 10, 34, 58,  4, 18, 46, 19, 29, 30, 55, 12,
         2, 49,  1, 27,  3, 56, 18, 42,  3, 45, 30, 17, 52, 11]])

## Ejercicios con transpose:


3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [23]:
array_3d2 = np.random.randint(1, 61, (3,4,5)) 
array_3d2

array([[[50, 31, 17, 59, 44],
        [39, 24, 54, 11, 33],
        [58, 46, 20, 50, 59],
        [ 5, 18, 57, 22,  1]],

       [[54, 54, 52, 41, 29],
        [45, 44,  9, 10, 34],
        [60, 53, 27, 29,  4],
        [31, 33, 27, 47, 45]],

       [[ 2, 60, 21, 27, 40],
        [33, 23, 56,  2, 22],
        [17, 50, 13, 51, 47],
        [41, 11,  4, 17, 32]]])

In [25]:
# Transpose
array_3d2_trans = np.transpose(array_3d2, (2,1,0))
array_3d2_trans

array([[[50, 54,  2],
        [39, 45, 33],
        [58, 60, 17],
        [ 5, 31, 41]],

       [[31, 54, 60],
        [24, 44, 23],
        [46, 53, 50],
        [18, 33, 11]],

       [[17, 52, 21],
        [54,  9, 56],
        [20, 27, 13],
        [57, 27,  4]],

       [[59, 41, 27],
        [11, 10,  2],
        [50, 29, 51],
        [22, 47, 17]],

       [[44, 29, 40],
        [33, 34, 22],
        [59,  4, 47],
        [ 1, 45, 32]]])

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [26]:
array_3d2_trans = np.transpose(array_3d2, (0,2,1))
array_3d2_trans

array([[[50, 39, 58,  5],
        [31, 24, 46, 18],
        [17, 54, 20, 57],
        [59, 11, 50, 22],
        [44, 33, 59,  1]],

       [[54, 45, 60, 31],
        [54, 44, 53, 33],
        [52,  9, 27, 27],
        [41, 10, 29, 47],
        [29, 34,  4, 45]],

       [[ 2, 33, 17, 41],
        [60, 23, 50, 11],
        [21, 56, 13,  4],
        [27,  2, 51, 17],
        [40, 22, 47, 32]]])

5. ¿Qué diferencia existe entre el reshape y el transpose?

**np.reshape():** cambia la forma de la matriz a la forma especificada. Mayor flexibilidad que transpose. \
**np.transpose():** invierte los ejes de nuestra matriz o si se le especifica el orden, nos permuta los ejes de la matriz. Invierte siguiendo el orden de posición. \

6. ¿Y entre el transpose y el swapaxes?

**np.transpose():** invierte los ejes de nuestra matriz o si se le especifica el orden, nos permuta los ejes de la matriz\
**np.swapaxes():** intercambia dos ejes de la matriz, indicando sobre que ejes queremos realizar la operación

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [27]:
tri_array = np.random.rand(2,3,5)
tri_array

array([[[0.12778955, 0.42153642, 0.47435985, 0.50517278, 0.52943898],
        [0.02808622, 0.18748348, 0.13911855, 0.496035  , 0.4600872 ],
        [0.69905858, 0.9253662 , 0.57815375, 0.39757717, 0.76313507]],

       [[0.34807389, 0.65894996, 0.15996369, 0.12781897, 0.9577742 ],
        [0.69591313, 0.10047609, 0.4875217 , 0.92940119, 0.39363867],
        [0.86872085, 0.16977055, 0.57393591, 0.5284691 , 0.02220416]]])

In [28]:
# Redondeo array

tri_array_redond = np.round(tri_array, 1)
tri_array_redond

array([[[0.1, 0.4, 0.5, 0.5, 0.5],
        [0. , 0.2, 0.1, 0.5, 0.5],
        [0.7, 0.9, 0.6, 0.4, 0.8]],

       [[0.3, 0.7, 0.2, 0.1, 1. ],
        [0.7, 0.1, 0.5, 0.9, 0.4],
        [0.9, 0.2, 0.6, 0.5, 0. ]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".

In [30]:
array_vacio = np.empty((2,3,5))
array_vacio

array([[[0.1, 0.4, 0.5, 0.5, 0.5],
        [0. , 0.2, 0.1, 0.5, 0.5],
        [0.7, 0.9, 0.6, 0.4, 0.8]],

       [[0.3, 0.7, 0.2, 0.1, 1. ],
        [0.7, 0.1, 0.5, 0.9, 0.4],
        [0.9, 0.2, 0.6, 0.5, 0. ]]])

In [32]:
# Si el valor del array es igual que la media, se reemplaza por "A".

array_A = np.where(array_vacio == np.mean(tri_array),"A", "Z")
array_A

array([[['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z']],

       [['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z']]], dtype='<U1')

In [38]:
# Si el valor del array es mayor que la media, se reemplaza por "B".

array_B = np.where(array_vacio > np.mean(tri_array),"B", "C")
array_B

array([[['C', 'C', 'B', 'B', 'B'],
        ['C', 'C', 'C', 'B', 'B'],
        ['B', 'B', 'B', 'C', 'B']],

       [['C', 'B', 'C', 'C', 'B'],
        ['B', 'C', 'B', 'B', 'C'],
        ['B', 'C', 'B', 'B', 'C']]], dtype='<U1')

In [35]:
# Si el valor del array es menor que la media, se reemplaza por "C".

array_C = np.where(array_vacio < np.mean(tri_array),"C", "Z")
array_C

array([[['C', 'C', 'Z', 'Z', 'Z'],
        ['C', 'C', 'C', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'C', 'Z']],

       [['C', 'Z', 'C', 'C', 'Z'],
        ['Z', 'C', 'Z', 'Z', 'C'],
        ['Z', 'C', 'Z', 'Z', 'C']]], dtype='<U1')

In [36]:
# Si el valor es igual que el máximo, se reemplaza por "D".

array_D = np.where(array_vacio == np.max(tri_array),"D", "Z")
array_D

array([[['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z']],

       [['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z']]], dtype='<U1')

In [37]:
# Si el valor es igual que el mínimo, se reemplaza por "E".

array_E = np.where(array_vacio == np.min(tri_array),"E", "Z")
array_E

array([[['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z']],

       [['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z'],
        ['Z', 'Z', 'Z', 'Z', 'Z']]], dtype='<U1')

In [ ]:
# SUMA
