# Creación e Indexación:


1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [23]:
import numpy as np

In [24]:
array1 = np.random.randint(10, 100, size = 50)
print(array1)

[33 84 55 94 93 92 27 22 29 72 89 73 61 95 42 97 96 34 70 11 52 32 82 91
 41 12 31 23 99 78 20 63 40 42 94 32 58 26 53 47 38 32 39 62 94 38 51 91
 32 29]


In [25]:
multiplos5 = array1[5::5]
multiplos5

array([92, 89, 97, 52, 12, 20, 32, 38, 38], dtype=int32)

2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [26]:
array2 = np.random.randint(1, 21, size = 30)
array2

array([ 1, 10, 10,  8, 17,  3, 11,  2,  9, 18,  4, 12, 17,  9,  7, 17, 16,
        6,  1, 15,  8,  1, 10, 19,  6,  9,  5, 19,  6,  2], dtype=int32)

In [27]:
array2[1::2]

array([10,  8,  3,  2, 18, 12,  9, 17,  6, 15,  1, 19,  9, 19,  2],
      dtype=int32)

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [28]:
array_sum1 =np.random.randint(0, 20, (4,6)) 
array_sum1

array([[ 9, 15,  2,  3,  1, 18],
       [ 2, 19, 13, 19,  8,  9],
       [ 2, 16, 15,  3,  9,  6],
       [ 6,  2,  2, 19, 19, 14]], dtype=int32)

In [29]:
array_sum2 =np.random.rand(4,6)
array_sum2

array([[0.45128767, 0.76106155, 0.87692461, 0.07833208, 0.03833656,
        0.68890099],
       [0.89120845, 0.09587201, 0.8656617 , 0.5994791 , 0.00507982,
        0.54097433],
       [0.16985499, 0.55838894, 0.83353208, 0.53219921, 0.12833818,
        0.24046577],
       [0.22754827, 0.44605078, 0.31323408, 0.45791486, 0.90166897,
        0.31419119]])

In [30]:
# Sumamos los dos array

suma_array = np.add(array_sum1, array_sum2)
suma_array

array([[ 9.45128767, 15.76106155,  2.87692461,  3.07833208,  1.03833656,
        18.68890099],
       [ 2.89120845, 19.09587201, 13.8656617 , 19.5994791 ,  8.00507982,
         9.54097433],
       [ 2.16985499, 16.55838894, 15.83353208,  3.53219921,  9.12833818,
         6.24046577],
       [ 6.22754827,  2.44605078,  2.31323408, 19.45791486, 19.90166897,
        14.31419119]])

In [31]:
# Redondeamos a 2 decimales

redondeo = np.round(suma_array, 2)
redondeo

array([[ 9.45, 15.76,  2.88,  3.08,  1.04, 18.69],
       [ 2.89, 19.1 , 13.87, 19.6 ,  8.01,  9.54],
       [ 2.17, 16.56, 15.83,  3.53,  9.13,  6.24],
       [ 6.23,  2.45,  2.31, 19.46, 19.9 , 14.31]])

In [32]:
# Accedo a la última fila de la matriz

ultima_fila = redondeo[-1]
ultima_fila

array([ 6.23,  2.45,  2.31, 19.46, 19.9 , 14.31])

4. BONUS: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

# Reshape y Transpose:


## Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [33]:
array_3d = np.random.randint(1, 101, (2,3,4)) 
array_3d

array([[[ 5, 53, 83, 40],
        [86, 88, 69, 67],
        [24, 37, 73, 76]],

       [[24, 19, 57, 20],
        [61, 25, 61,  7],
        [80, 36, 78, 56]]], dtype=int32)

In [34]:
array_reshape = np.reshape(array_3d,(12,2))
array_reshape

array([[ 5, 53],
       [83, 40],
       [86, 88],
       [69, 67],
       [24, 37],
       [73, 76],
       [24, 19],
       [57, 20],
       [61, 25],
       [61,  7],
       [80, 36],
       [78, 56]], dtype=int32)

In [35]:
np.reshape?

Signature:       np.reshape(a, /, shape=None, *, newshape=None, order='C', copy=None)
Call signature:  np.reshape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function reshape at 0x000002A4E7ECC400>
File:            c:\users\anabo\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
shape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
newshape : int or tuple of ints
    .. deprecated:: 2.1
        Replaced by ``shape`` argument. Retained for backward
        compatibility.
order : {'C', 'F', 'A'}, optional
    Read the elements of ``a`` using this ind

In [36]:
# Order (C y F)

array_reshape = np.reshape(array_3d,(12,2),order='C')
array_reshape


array([[ 5, 53],
       [83, 40],
       [86, 88],
       [69, 67],
       [24, 37],
       [73, 76],
       [24, 19],
       [57, 20],
       [61, 25],
       [61,  7],
       [80, 36],
       [78, 56]], dtype=int32)

In [37]:

array_reshape = np.reshape(array_3d,(12,2), order='F')
array_reshape

array([[ 5, 83],
       [24, 57],
       [86, 69],
       [61, 61],
       [24, 73],
       [80, 78],
       [53, 40],
       [19, 20],
       [88, 67],
       [25,  7],
       [37, 76],
       [36, 56]], dtype=int32)

2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [38]:
array_3d2 = np.random.randint(1, 61, (3,4,5)) 
array_3d2

array([[[15, 59, 43, 11, 18],
        [48, 43, 47,  6, 59],
        [ 4, 55, 36, 50, 40],
        [14, 40,  5, 18,  7]],

       [[ 7, 26, 48, 47,  8],
        [43, 23,  3, 28, 30],
        [25, 17, 22, 24, 51],
        [49, 50, 38, 40,  7]],

       [[37,  2, 23,  8,  3],
        [55, 47, 16, 27, 20],
        [60, 36, 42, 59,  5],
        [17, 18, 40, 21, 56]]], dtype=int32)

In [39]:
array_reshape2 = np.reshape(array_3d2,(2,30))
array_reshape2

array([[15, 59, 43, 11, 18, 48, 43, 47,  6, 59,  4, 55, 36, 50, 40, 14,
        40,  5, 18,  7,  7, 26, 48, 47,  8, 43, 23,  3, 28, 30],
       [25, 17, 22, 24, 51, 49, 50, 38, 40,  7, 37,  2, 23,  8,  3, 55,
        47, 16, 27, 20, 60, 36, 42, 59,  5, 17, 18, 40, 21, 56]],
      dtype=int32)

## Ejercicios con transpose:


3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [40]:
array_3d2 = np.random.randint(1, 61, (3,4,5)) 
array_3d2

array([[[50, 56, 15, 10, 29],
        [27, 37, 12,  5,  8],
        [16, 13, 36, 33, 20],
        [24, 32,  7, 16, 46]],

       [[53, 52, 17, 31, 39],
        [19,  9, 25,  8, 13],
        [41, 41,  8,  9, 20],
        [25,  4, 53, 34,  2]],

       [[12,  5,  4,  8, 59],
        [38, 52, 23, 40, 46],
        [58, 30, 25, 26, 12],
        [33, 30, 15, 17, 54]]], dtype=int32)

In [41]:
# Transpose
array_3d2_trans = np.transpose(array_3d2, (2,1,0))
array_3d2_trans

array([[[50, 53, 12],
        [27, 19, 38],
        [16, 41, 58],
        [24, 25, 33]],

       [[56, 52,  5],
        [37,  9, 52],
        [13, 41, 30],
        [32,  4, 30]],

       [[15, 17,  4],
        [12, 25, 23],
        [36,  8, 25],
        [ 7, 53, 15]],

       [[10, 31,  8],
        [ 5,  8, 40],
        [33,  9, 26],
        [16, 34, 17]],

       [[29, 39, 59],
        [ 8, 13, 46],
        [20, 20, 12],
        [46,  2, 54]]], dtype=int32)

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [42]:
array_3d2_trans = np.transpose(array_3d2, (0,2,1))
array_3d2_trans

array([[[50, 27, 16, 24],
        [56, 37, 13, 32],
        [15, 12, 36,  7],
        [10,  5, 33, 16],
        [29,  8, 20, 46]],

       [[53, 19, 41, 25],
        [52,  9, 41,  4],
        [17, 25,  8, 53],
        [31,  8,  9, 34],
        [39, 13, 20,  2]],

       [[12, 38, 58, 33],
        [ 5, 52, 30, 30],
        [ 4, 23, 25, 15],
        [ 8, 40, 26, 17],
        [59, 46, 12, 54]]], dtype=int32)

5. ¿Qué diferencia existe entre el reshape y el transpose?

**np.reshape():** cambia la forma de la matriz a la forma especificada. Mayor flexibilidad que transpose. \
**np.transpose():** invierte los ejes de nuestra matriz o si se le especifica el orden, nos permuta los ejes de la matriz. Invierte siguiendo el orden de posición. \

6. ¿Y entre el transpose y el swapaxes?

**np.transpose():** invierte los ejes de nuestra matriz o si se le especifica el orden, nos permuta los ejes de la matriz\
**np.swapaxes():** intercambia dos ejes de la matriz, indicando sobre que ejes queremos realizar la operación

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [43]:
tri_array = np.random.rand(2,3,5)
tri_array

array([[[0.09476029, 0.39936529, 0.58707974, 0.01080474, 0.11520199],
        [0.13932366, 0.63710744, 0.42595659, 0.70783941, 0.19206453],
        [0.55341899, 0.78369451, 0.16200011, 0.89771294, 0.8508177 ]],

       [[0.59561621, 0.35860814, 0.99093078, 0.09045788, 0.8650329 ],
        [0.30129298, 0.75603038, 0.99798012, 0.36582647, 0.60700119],
        [0.39857864, 0.29965   , 0.33767088, 0.46021762, 0.46205394]]])

In [44]:
# Redondeo array

tri_array_redond = np.round(tri_array, 1)
tri_array_redond

array([[[0.1, 0.4, 0.6, 0. , 0.1],
        [0.1, 0.6, 0.4, 0.7, 0.2],
        [0.6, 0.8, 0.2, 0.9, 0.9]],

       [[0.6, 0.4, 1. , 0.1, 0.9],
        [0.3, 0.8, 1. , 0.4, 0.6],
        [0.4, 0.3, 0.3, 0.5, 0.5]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".

In [57]:

# Creamos un array vacío con las dimensiones del array tri_array_redond

array_vacio = np.empty((2,3,5))
array_vacio

array([[[0.09476029, 0.39936529, 0.58707974, 0.01080474, 0.11520199],
        [0.13932366, 0.63710744, 0.42595659, 0.70783941, 0.19206453],
        [0.55341899, 0.78369451, 0.16200011, 0.89771294, 0.8508177 ]],

       [[0.59561621, 0.35860814, 0.99093078, 0.09045788, 0.8650329 ],
        [0.30129298, 0.75603038, 0.99798012, 0.36582647, 0.60700119],
        [0.39857864, 0.29965   , 0.33767088, 0.46021762, 0.46205394]]])

In [59]:
# Calculamos la media del array tri_array_redond (iniciales TAR)

media_TAR= np.mean(tri_array_redond)
min_TAR = np.min(tri_array_redond)
max_TAR = np.max(tri_array_redond)

# Preparamos la máscara con las condiciones mediante where anidados.

array_mascara = np.where(array_vacio == media_TAR,"A", np.where(array_vacio > media_TAR,"B", np.where(array_vacio < media_TAR,"C", np.where(array_vacio == max_TAR,"D", np.where(array_vacio == min_TAR,"E", "Z")))))

array_mascara

array([[['C', 'C', 'B', 'C', 'C'],
        ['C', 'B', 'C', 'B', 'C'],
        ['B', 'B', 'C', 'B', 'B']],

       [['B', 'C', 'B', 'C', 'B'],
        ['C', 'B', 'B', 'C', 'B'],
        ['C', 'C', 'C', 'C', 'C']]], dtype='<U1')