In [1]:
import pandas as pd
import numpy as np
import random

1. ¿Qué diferencia hay entre una Serie y un DataFrame?\
La *serie* es una estructura de datos unidimensional, mientras que el *DataFrame* es una estructura de datos bidimensional que sirve para el analisis de datos tabulares (forma de tabla).\
Una serie solo admite un tipo de datos, y el Datafrma puede combinar diferentes tipos de datos.

2. SERIES. Contesta a las siguientes preguntas:

- Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

- A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

- A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

In [2]:
# Creo las listas primero.
valores = [random.randint(1, 10) for _ in range(7)]
indices = ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"]

print(f"Lista de mis valores: {valores}")
print(f"Lista de mis índices: {indices}")

Lista de mis valores: [5, 2, 3, 1, 9, 3, 3]
Lista de mis índices: ['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']


In [3]:
# Creo mis series a partir de las lista creadas.
serie_valores = pd.Series(valores)
serie_indices = pd.Series(indices)

print(f"La serie creada a partir de la lista valores es:\n{serie_valores}")
print(f"La serie creada a partir de la lista índices es:\n{serie_indices}")


La serie creada a partir de la lista valores es:
0    5
1    2
2    3
3    1
4    9
5    3
6    3
dtype: int64
La serie creada a partir de la lista índices es:
0        lunes
1       martes
2    miércoles
3       jueves
4      viernes
5       sábado
6      domingo
dtype: object


In [4]:
serie_combinada = pd.Series(valores, index=indices)
print(f"La serie creada a partir de la combinacion de listas es:\n{serie_combinada}")

La serie creada a partir de la combinacion de listas es:
lunes        5
martes       2
miércoles    3
jueves       1
viernes      9
sábado       3
domingo      3
dtype: int64


In [5]:
print(valores)
print(indices)

[5, 2, 3, 1, 9, 3, 3]
['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']


In [6]:
# Creo un diccionario usando un bucle for usando el método zip que nos permite iterar por dos listas a la vez.
# Se pasan dos iterables.
zip_pandas = zip(valores,indices)
set_zip = set(zip_pandas)
print(set_zip)

{(5, 'lunes'), (1, 'jueves'), (9, 'viernes'), (2, 'martes'), (3, 'sábado'), (3, 'domingo'), (3, 'miércoles')}


In [8]:
dicc_set = {}

# Iteras sobre el set, cada tupla es lo que hay dentro del parentesis.
for tupla in set_zip:
    dicc_set[tupla[1]] = tupla[0]
print(dicc_set)

{'lunes': 5, 'jueves': 1, 'viernes': 9, 'martes': 2, 'sábado': 3, 'domingo': 3, 'miércoles': 3}


- Crea una Serie con el diccionario creado en el punto anterior.

¿Qué forma tiene esta última Serie?

¿Qué tipo de datos tiene?

¿Qué tamaño tiene?

¿Cuáles son los índices de la Serie?

¿Y los values?

- Extrae el valor para el índice "lunes"

- Extrae el valor para el índice "lunes", "martes" y "miércoles".

- Extrae el valor para el índice "lunes" y "domingo".

In [10]:
serie = pd.Series(dicc_set)
print(f"Esta es mi serie:\n{serie}")

Esta es mi serie:
lunes        5
jueves       1
viernes      9
martes       2
sábado       3
domingo      3
miércoles    3
dtype: int64


In [13]:
# Muestro la forma de la última serie.
print(f"La forma de la Serie es: {serie.shape}")


# Muestro el tipo de datos.
print(f"El tipo de datos de la Serie es: {serie.dtypes}")


# Muestro el tamaño.
print(f"El número de elementos/tamaño de la Serie es: {serie.size}")


# Muestro los índices.
print(f"Los índices de la Serie son: {serie.index}")


# Muestro los valores/values.
print(f"Los valores de la Serie son: {serie.values}")


# Muestro el valor para el índice "lunes".
print(f"El valor que está en índice 'lunes' es: {serie["lunes"]}") 


# Muestro los valores para los índices "lunes", "martes" y "miércoles" DOBLE CORCHETE CUANDO BUSCAS LOS VALORES PARA MAS DE UNA COLUMNA.
print(f"Los valores que están en los índices 'lunes', 'martes' y 'miércoles' son:\n{serie[["lunes", "martes", "miércoles"]]}") 


# Muestro los valores para los índices  "lunes" y "domingo" DOBLE CORCHETE CUANDO BUSCAS LOS VALORES PARA MAS DE UNA COLUMNA.
print(f"Los valores que están en los índices 'lunes' y 'domingo' son:\n{serie[["lunes", "domingo"]]}") 

La forma de la Serie es: (7,)
El tipo de datos de la Serie es: int64
El número de elementos/tamaño de la Serie es: 7
Los índices de la Serie son: Index(['lunes', 'jueves', 'viernes', 'martes', 'sábado', 'domingo',
       'miércoles'],
      dtype='object')
Los valores de la Serie son: [5 1 9 2 3 3 3]
El valor que está en índice 'lunes' es: 5
Los valores que están en los índices 'lunes', 'martes' y 'miércoles' son:
lunes        5
martes       2
miércoles    3
dtype: int64
Los valores que están en los índices 'lunes' y 'domingo' son:
lunes      5
domingo    3
dtype: int64


3. DataFrames

- Crea un array de dos dimensiones con 4 filas y 3 columnas.

- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

- Descarga el archivo "medallas" y carga el DataFrame.

- Usando el loc extrae todas las columnas de la fila de Tailandia.

- Usando el loc extrae todas las columnas de China e Irán.

- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

- Usando el iloc extrae la información de la India. Devolved todas las columnas.

- Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

- Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

In [16]:
# Creo mi array.
array = np.random.randint(0,100,(4,3))
print(f"Este es mi array:\n{array}")

Este es mi array:
[[89  1 79]
 [46 70 81]
 [ 0 41 13]
 [92 17 91]]


In [18]:
# Convierto mi array en DataFrame.
df_array = pd.DataFrame(array, columns=["España", "Francia", "Italia"])
print(f"Este es mi array convertido a DataFrame:\n{df_array}")

Este es mi array convertido a DataFrame:
   España  Francia  Italia
0      89        1      79
1      46       70      81
2       0       41      13
3      92       17      91


In [36]:
# Descargo el archivo csv medallas y cargo el DataFrame.
df_medallas = pd.read_csv("medallas.csv", index_col=1)
df_medallas

Indice   Oro  Plata  Bronce
País                                        
China                 1  1473    994     720
Japón                 2  1032   1037     985
Corea del Sur         3   745    663     827
Irán                  4   179    181     197
Kazajistán            5   155    158     224
India                 6   154    202     315
Tailandia             7   132    175     278
Indonesia             8   112    131     240
China Taipéi          9    99    144     276
Corea del Norte      10    91    120     235

- Usando el loc extrae todas las columnas de la fila de Tailandia.

- Usando el loc extrae todas las columnas de China e Irán.

- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

- Usando el iloc extrae la información de la India. Devolved todas las columnas.

- Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

- Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

In [43]:
tailandia = df_medallas.loc["Tailandia", "Oro":"Bronce"]
tailandia

Oro       132
Plata     175
Bronce    278
Name: Tailandia, dtype: int64

In [44]:
china_iran = df_medallas.loc[["China", "Irán"],"Oro":"Bronce"]
china_iran

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [45]:
india = df_medallas.iloc[5,1:]
india

Oro       154
Plata     202
Bronce    315
Name: India, dtype: int64

In [46]:
paises_impares = df_medallas.iloc[1::2,:]
paises_impares

Indice   Oro  Plata  Bronce
País                                        
Japón                 2  1032   1037     985
Irán                  4   179    181     197
India                 6   154    202     315
Indonesia             8   112    131     240
Corea del Norte      10    91    120     235

In [47]:
paises_impares = df_medallas.iloc[1::2,1:]
paises_impares

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

- Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [52]:
condicion1 = df_medallas.loc[df_medallas["Oro"]> 200, ["País"]]
condicion1 

KeyError: "None of [Index(['País'], dtype='object')] are in the [columns]"

In [ ]:
# Creo una nueva columna.
